<?php

namespace Proxies\__CG__\VesselBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Shipdetails extends \VesselBundle\Entity\Shipdetails implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'id', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'shipName', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'shipType', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'companyName', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'imoNumber', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'country', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'description', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'location', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'manufacturingYear', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'built', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'size', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'createdDate', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'gt'];
        }

        return ['__isInitialized__', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'id', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'shipName', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'shipType', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'companyName', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'imoNumber', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'country', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'description', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'location', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'manufacturingYear', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'built', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'size', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'createdDate', '' . "\0" . 'VesselBundle\\Entity\\Shipdetails' . "\0" . 'gt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Shipdetails $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', []);

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', []);

        return parent::setCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function setShipName($shipName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShipName', [$shipName]);

        return parent::setShipName($shipName);
    }

    /**
     * {@inheritDoc}
     */
    public function getShipName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShipName', []);

        return parent::getShipName();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getShipType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShipType', []);

        return parent::getShipType();
    }

    /**
     * {@inheritDoc}
     */
    public function setShipType($shipType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShipType', [$shipType]);

        return parent::setShipType($shipType);
    }

    /**
     * {@inheritDoc}
     */
    public function getImoNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImoNumber', []);

        return parent::getImoNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setImoNumber($imoNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImoNumber', [$imoNumber]);

        return parent::setImoNumber($imoNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyDetailsId($companyDetailsId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyDetailsId', [$companyDetailsId]);

        return parent::setCompanyDetailsId($companyDetailsId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyDetailsId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyDetailsId', []);

        return parent::getCompanyDetailsId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturingYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturingYear', []);

        return parent::getManufacturingYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturingYear($manufacturingYear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturingYear', [$manufacturingYear]);

        return parent::setManufacturingYear($manufacturingYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuilt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuilt', []);

        return parent::getBuilt();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuilt($built)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuilt', [$built]);

        return parent::setBuilt($built);
    }

    /**
     * {@inheritDoc}
     */
    public function getSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', []);

        return parent::getSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setSize($size)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', [$size]);

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getGt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGt', []);

        return parent::getGt();
    }

    /**
     * {@inheritDoc}
     */
    public function setGt($gt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGt', [$gt]);

        return parent::setGt($gt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyName', []);

        return parent::getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyName($companyName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyName', [$companyName]);

        return parent::setCompanyName($companyName);
    }

}
