<?php

namespace RankingBundle\Repository;

/**
 * RankingKpiRulesDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingKpiRulesDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
