<?php

namespace RankingBundle\Repository;

/**
 * RankingRulesDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingRulesDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
