<?php

namespace RankingBundle\Repository;

/**
 * RankingMonthlyDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingMonthlyDataRepository extends \Doctrine\ORM\EntityRepository
{
}
