<?php

namespace RankingBundle\Repository;

/**
 * RankingRulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingRulesRepository extends \Doctrine\ORM\EntityRepository
{
}
