<?php

namespace RankingBundle\Repository;

/**
 * RankingLookupStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingLookupStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
