<?php

namespace RankingBundle\Repository;

/**
 * RankingElementDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingElementDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
