<?php

namespace RankingBundle\Repository;

/**
 * RankingLookupDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingLookupDataRepository extends \Doctrine\ORM\EntityRepository
{
}
