<?php

namespace RankingBundle\Repository;

/**
 * ScorecardLookupStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScorecardLookupStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
