<?php

namespace RankingBundle\Repository;

/**
 * ScorecardLookupDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScorecardLookupDataRepository extends \Doctrine\ORM\EntityRepository
{
}
