<?php

namespace VesselBundle\Repository;

/**
 * AppsCountriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppsCountriesRepository extends \Doctrine\ORM\EntityRepository
{
}
