<?php

namespace VesselBundle\Repository;

/**
 * EmailUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
