<?php

namespace VesselBundle\Repository;

/**
 * EmailGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
