<?php

namespace VesselBundle\Repository;

/**
 * mailingdetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mailingdetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
