<?php

namespace VesselBundle\Repository;

/**
 * ShipTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
