<?php

namespace VesselBundle\Repository;

/**
 * ShipStatusDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipStatusDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
