<?php

namespace VesselBundle\Repository;

/**
 * ShipdetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipdetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
