<?php

namespace DashboardBundle\Repository;

/**
 * BodyAreasAffectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BodyAreasAffectedRepository extends \Doctrine\ORM\EntityRepository
{
}
