<?php

namespace DashboardBundle\Repository;

/**
 * ContainerPollutionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContainerPollutionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
