<?php

namespace DashboardBundle\Repository;

/**
 * FactortoIncidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactortoIncidentRepository extends \Doctrine\ORM\EntityRepository
{
}
