<?php

namespace DashboardBundle\Repository;

/**
 * HazardTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HazardTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
