<?php

namespace DashboardBundle\Repository;

/**
 * IncidentFirstInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidentFirstInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
