<?php

namespace DashboardBundle\Repository;

/**
 * IncidentCostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidentCostRepository extends \Doctrine\ORM\EntityRepository
{
}
