<?php

namespace DashboardBundle\Repository;

/**
 * IncidentDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidentDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
