<?php

namespace DashboardBundle\Repository;

/**
 * IncidentStatisticsDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidentStatisticsDataRepository extends \Doctrine\ORM\EntityRepository
{
}
