<?php

namespace DashboardBundle\Repository;

/**
 * IncidentOperatorWeatherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidentOperatorWeatherRepository extends \Doctrine\ORM\EntityRepository
{
}
