<?php

namespace DashboardBundle\Repository;

/**
 * OperationattimeofIncidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationattimeofIncidentRepository extends \Doctrine\ORM\EntityRepository
{
}
