<?php

namespace DashboardBundle\Repository;

/**
 * PlaceofAccidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceofAccidentRepository extends \Doctrine\ORM\EntityRepository
{
}
