<?php

namespace DashboardBundle\Repository;

/**
 * SeaPollutionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeaPollutionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
