<?php

namespace DashboardBundle\Repository;

/**
 * ShipOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
