<?php

namespace DashboardBundle\Repository;

/**
 * TypeofInjuryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeofInjuryRepository extends \Doctrine\ORM\EntityRepository
{
}
