<?php

namespace DashboardBundle\Repository;

/**
 * TypeofIncidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeofIncidentRepository extends \Doctrine\ORM\EntityRepository
{
}
