<?php

namespace DashboardBundle\Repository;

/**
 * TypeofCauseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeofCauseRepository extends \Doctrine\ORM\EntityRepository
{
}
