<?php

namespace UserBundle\Repository;

/**
 * CompanyUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
