<?php

namespace UserBundle\Repository;

/**
 * LogDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
